### ISSUE TITLE
flexible docking issue

### ISSUE THREAD

**Issue by ld139** [gnina/gnina#274]
### Issue summary
Dear authors:
     When using the binary version of GNINA to perform flexible docking, this error has occasionally occurred in some protein-ligand pairs. Sometimes, running the docking process one more time can resolve the issue. But it's troublesome to dock multiple protein-ligand pairs using a script.

```
gnina v1.1 master:e4cb380+   Built Dec 18 2023.
gnina is based on smina and AutoDock Vina.
Please cite appropriately.
```

Commandline: 
```
gnina -r ./test/apo2holo_datasets/group2/1prgA/Complex/2HWQA_101/Pocket_10A.pdb -l ./test/apo2holo_datasets/group2/1prgA/Complex/2HWQA_101/2HWQA_101_ligand_rdkit.sdf --autobox_ligand ./test/apo2holo_datasets/group2/1prgA/Complex/2HWQA_101/2HWQA_101_ligand_rdkit.sdf --autobox_add 10 --num_modes 40 -o ./test/apo2holo_datasets/group2/1prgA/Complex/2HWQA_101/gnina_flex_dock_2HWQA.sdf --exhaustiveness 32 --flexdist_ligand ./test/apo2holo_datasets/group2/1prgA/Complex/2HWQA_101/2HWQA_101_ligand_rdkit.sdf --flexdist 3.5 --no_gpu
```

```
==============================
*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL file (title is 2HWQA_101)

==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders

==============================
*** Open Babel Warning  in ReadMolecule
  Failed to kekulize aromatic bonds in MOL file (title is 2HWQA_101)

Flexible residues: A:60 A:76 A:79 A:80 A:82 A:158 A:161 A:243 A:247 A:259 A:263
Using random seed: -1234409216

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***********************terminate called after throwing an instance of 'numerical_error'
  what():  Numerical degeneracy encountered. Check for non-physical inputs. nan should be between -pi and pi.
*** Aborted at 1724313213 (unix time) try "date -d @1724313213" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800004760) received by PID 18272 (TID 0x7f34917fa000) from PID 18272; stack trace: ***
    @     0x7f34f5ee5520 (unknown)
    @     0x7f34f5f39a7c pthread_kill
    @     0x7f34f5ee5476 raise
    @     0x7f34f5ecb7f3 abort
    @     0x7f34f6276bbe (unknown)
    @     0x7f34f628224c (unknown)
    @     0x7f34f62822b7 std::terminate()
    @     0x7f34f6282518 __cxa_throw
    @           0x591fd4 normalize_angle()
    @           0x593ee4 bfgs<>()
    @           0x590bfd quasi_newton::operator()()
    @           0x5622d9 monte_carlo::operator()()
    @           0x5737b2 parallel_mc_aux::operator()()
    @           0x56f5a4 _ZN5boost6detail11thread_dataINS_17reference_wrapperIN12parallel_forIN13parallel_iterI15parallel_mc_auxNS_10ptr_vectorI16parallel_mc_taskNS_20heap_clone_allocatorEvEES7_ZNK11parallel_mcclERK5modelRNS6_I11output_typeS8_vEERK12precalculateR5igridRK3vecSO_RNS_6random23mersenne_twister_engineIjLm32ELm624ELm397ELm31ELj2567483615ELm11ELj4294967295ELm7ELj2636928640ELm15ELj4022730752ELm18ELj1812433253EEER4gridR9non_cacheEUlvE_Lb1EE3auxESX_Lb1EE3auxEEEE3runEv
    @           0x81f24e thread_proxy
    @     0x7f34f5f37b43 (unknown)
    @     0x7f34f5fc9a00 (unknown)
    @                0x0 (unknown)
Aborted
```

### Your system configuration
Operating system: WLS2 ubuntu
Compiler: gcc 7.5.0
CUDA version (if applicable): 11.5 
CUDNN version (if applicable):
Python version: 3.16

**Comment by dkoes** [comment]
I am pretty sure this is fixed in the latest version of the code.  Can you try checking it out and testing it with your data?

**Comment by DingLuoXMU** [comment]
Dear Prof. Koes, I have checked my GNINA version and re-downloaded the binary v1.1 version of GNINA, but the error still occurs, whether using or not using the GPU for docking. This is a failed example.
[4FGYA_601.zip](https://github.com/user-attachments/files/16721031/4FGYA_601.zip)

**Comment by dkoes** [comment]
By latest version I mean what is in git, not the last release.

**Comment by metma99** [comment]
Can you please post a link, Prof. Koes?

**Comment by dkoes** [comment]
A link to what? The github you are posting issues on??

**Comment by metma99** [comment]
I do not know how to retrieve ' latest version I mean what is in git'. Markus

**Comment by RMeli** [comment]
You need to follow the [Installation Instructions](https://github.com/gnina/gnina?tab=readme-ov-file#installation) to install GNINA from source.

In particular, the command
```
git clone https://github.com/gnina/gnina.git
```
will get you the latest version of the _source code_ locally. Then you need to compile it.

There is no pre-compiled nightly version.
